### ISSUE TITLE
Unable to resolve the request "site/error"

### ISSUE THREAD

**Issue by yanshiqiang** [a-giovani17/yii2-rest-api#1]
Great Job!.
But when I visit  http://localhost/, I get the error messages  as blow 
=====
An Error occurred while handling another error:
exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "site/error".' in /opt/yii2/basic/vendor/yiisoft/yii2/base/Module.php:537
Stack trace:
#0 /opt/yii2/basic/vendor/yiisoft/yii2/web/ErrorHandler.php(97): yii\base\Module->runAction('site/error')
#1 /opt/yii2/basic/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
exception 'yii\web\NotFoundHttpException' with message 'Page not found.' in /opt/yii2/basic/vendor/yiisoft/yii2/web/Request.php:281
Stack trace:
#0 /opt/yii2/basic/vendor/yiisoft/yii2/web/Application.php(82): yii\web\Request->resolve()
#1 /opt/yii2/basic/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /opt/yii2/basic/web/index.php(12): yii\base\Application->run()
#3 {main}
====

How to solve it ? 
Thank you.

**Comment by yanshiqiang** [comment]
BTW, When I visit http://localhost/auth  or http://localhost./orders is ok

**Comment by a-giovani17** [comment]
Hello,

It's default error handling by Yii2, seems like I forgot to add SiteController.php file.
Please check it out https://github.com/a-giovani17/yii2-rest-api/commit/756eff5e574f2bd5dd5c4047e5f857c6966090a2

You can change the error handling's action in config/web.php too (at line 29)
`
'errorHandler' => [
            'errorAction' => 'site/error',
        ],
`

Hope this helps. Thank you.
