### ISSUE TITLE
The token could implemented by JWT？

### ISSUE THREAD

**Issue by yanshiqiang** [a-giovani17/yii2-rest-api#2]
hi:
  I see the codes that the token is using uuid. The better way should use jwt？If using JWT，maybe use yii2 behaviors？
Next version should support it?

**Comment by a-giovani17** [comment]
Hello,
I used uuid for simplicity, but using jwt seems good idea. I consider to support it in next version.

Maybe using this package:
https://packagist.org/packages/msheng/yii2-jwt

**Comment by yanshiqiang** [comment]
https://github.com/damirka/yii2-jwt，this package maybe better.

**Comment by yanshiqiang** [comment]
other package is https://github.com/sizeg/yii2-jwt
